-- Script d'initialisation de la base de données Oracle (Nettoyé pour Python)

-- On utilise le séparateur custom -- SEPARATOR --
-- Suppression des vues
BEGIN EXECUTE IMMEDIATE 'DROP VIEW V_CHIFFRE_AFFAIRES_CLIENT'; EXCEPTION WHEN OTHERS THEN NULL; END;
-- SEPARATOR --
BEGIN EXECUTE IMMEDIATE 'DROP VIEW V_PRODUITS_POPULAIRES'; EXCEPTION WHEN OTHERS THEN NULL; END;
-- SEPARATOR --

-- Suppression des tables
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DETAILS_COMMANDES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
-- SEPARATOR --
BEGIN EXECUTE IMMEDIATE 'DROP TABLE COMMANDES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
-- SEPARATOR --
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PRODUITS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
-- SEPARATOR --
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CLIENTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
-- SEPARATOR --

-- Création des tables
CREATE TABLE CLIENTS (
    CLIENT_ID NUMBER PRIMARY KEY,
    NOM VARCHAR2(100) NOT NULL,
    PRENOM VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(255) UNIQUE NOT NULL,
    VILLE VARCHAR2(100),
    DATE_INSCRIPTION DATE DEFAULT SYSDATE
)
-- SEPARATOR --
CREATE TABLE PRODUITS (
    PRODUIT_ID NUMBER PRIMARY KEY,
    LIBELLE VARCHAR2(255) NOT NULL,
    CATEGORIE VARCHAR2(100),
    PRIX_UNITAIRE NUMBER(10, 2) NOT NULL,
    STOCK NUMBER DEFAULT 0
)
-- SEPARATOR --
CREATE TABLE COMMANDES (
    COMMANDE_ID NUMBER PRIMARY KEY,
    CLIENT_ID NUMBER REFERENCES CLIENTS (CLIENT_ID),
    DATE_COMMANDE DATE DEFAULT SYSDATE,
    STATUT VARCHAR2(50),
    MONTANT_TOTAL NUMBER(10, 2)
)
-- SEPARATOR --
CREATE TABLE DETAILS_COMMANDES (
    DETAIL_ID NUMBER PRIMARY KEY,
    COMMANDE_ID NUMBER REFERENCES COMMANDES (COMMANDE_ID),
    PRODUIT_ID NUMBER REFERENCES PRODUITS (PRODUIT_ID),
    QUANTITE NUMBER NOT NULL,
    PRIX_LIGNE NUMBER(10, 2)
)
-- SEPARATOR --

-- Création des vues
CREATE OR REPLACE VIEW V_CHIFFRE_AFFAIRES_CLIENT AS
SELECT C.NOM, C.PRENOM, SUM(O.MONTANT_TOTAL) AS TOTAL_DEPENSE
FROM CLIENTS C
    JOIN COMMANDES O ON C.CLIENT_ID = O.CLIENT_ID
GROUP BY
    C.NOM,
    C.PRENOM
    -- SEPARATOR --
CREATE OR REPLACE VIEW V_PRODUITS_POPULAIRES AS
SELECT P.LIBELLE, SUM(DC.QUANTITE) AS TOTAL_VENDU
FROM
    PRODUITS P
    JOIN DETAILS_COMMANDES DC ON P.PRODUIT_ID = DC.PRODUIT_ID
GROUP BY
    P.LIBELLE